"""empty message

Revision ID: 37f7cb77a4ac
Revises: 78128a077786
Create Date: 2023-03-13 15:15:32.090302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f7cb77a4ac'
down_revision = '78128a077786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propertytype', sa.String(length=255), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('propertytype')

    # ### end Alembic commands ###
