"""empty message

Revision ID: 78128a077786
Revises: f8a7464c4e77
Create Date: 2023-03-12 21:02:32.173793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78128a077786'
down_revision = 'f8a7464c4e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))
        batch_op.drop_column('property_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
