"""empty message

Revision ID: f8a7464c4e77
Revises: 1895a5633079
Create Date: 2023-03-12 20:58:32.975799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a7464c4e77'
down_revision = '1895a5633079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type', sa.String(length=255), nullable=True))
        batch_op.drop_column('propertytype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propertytype', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('property_type')

    # ### end Alembic commands ###
